language: node_js
node_js:
  - 'stable'
<<<<<<< HEAD
services:
  - mongodb
=======
>>>>>>> origin/development
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
env:
  - CXX=g++-5
sudo: required
# safelist
branches:
  only:
  - master
  - staging
  - development

  # except:
  #   -
before_script: npm i
script:
  # - npm run lint
<<<<<<< HEAD
  - npm test
=======
  - npm test
>>>>>>> origin/development
